# Generated by Django 5.0.1 on 2024-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_userprofile_confirm_password_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='seller', max_length=128),
            preserve_default=False,
        ),
    ]
